<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	// form kontak
	'Contact' => 'Kontak',
	'Fields with ' => 'Field dengan tanda ',
	'are required.' => 'Harus di isi',
	'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => 'Jika anda memiliki request atau pertanyaan, Mohon isi form di bawah untuk menghubungi kamu, Terima Kasih.',
	'Letters are not case-sensitive.' => 'Huruf besar / kecil tidak berpengaruh',
	'Please enter the letters as they are shown in the image above.' => 'Masukkan huruf yang terlihat pada gambar di atas',
	// page Site
	'Branch'=>'Cabang',
	'PC Users'=>'Komputer User',
	'Member'=>'Pengaturan Pengguna',
	'Logout ('=>'Keluar (',
	'Help'=>'Bantuan',
	'Logout'=>'Keluar',
	'Login'=>'Masuk',
	'Create '=>'Data Baru ',
	'Add '=>'Tambahkan ',
	'Save'=>'Simpan',
	'create'=>'Data Baru',
	'Manage '=>'Management ',
	'Update '=>'Edit ',
	'View '=>'Detail ',
	'Delete '=>'Hapus ',
	'List '=>'Data ',
	'result'=>'Hasil',
	'Fields with'=>'Form dengan tanda',
	'(calendar appears when textbox is clicked)'=>'(Kalender akan muncul Ketika textbox kalender di klik)',
	// Model Branch
	'Branchs'=>'Cabang',
	'Name'=>'Nama',
	'Description'=>'Deskripsi',
	'Address'=>'Alamat',
	'Parent Office'=>'Kantor Induk',
	'Last Visit'=>'Tanggal Kunjungan Terakhir',
	'Recent CPU Licenses'=>'Penambahan Lisensi Terbaru',
	'Added '=>'Ditambahkan',
	'License'=>'Lisensi',
	'Displaying'=>'Menampilkan',
	'Recent CPU Licenses'=>'Lisensi Terbaru',
	'added a License.'=>'menambahkan lisensi',
	// Model User
	'Users'=>'Akun Pengguna',
	'User'=>'Akun Pengguna',
	'My User'=>'Akun saya',
	'Username'=>'Nama Pengguna',
	'Password'=>'Password',
	'Repeat Password'=>'Ulangi Password',
	'Last Login Time'=>'Terakhir kali login',
	'Authorisation'=>'Otorisasi',
	// Model PC Users
	'PC User'=>'Pengguna PC',
	'Division'=>'Divisi',
	'Type'=>'Tipe PC',
	'Office(Physical)'=>'Office(Fisik COA)',
	'Label Coa(Physical)'=>'Label Coa(Tertempel di CPU)',
	'File Name'=>'Nama File Siw',
	'IP Address'=>'Nomor IP',
	'Collapse All'=>'Tutup Semua Cabang',
	'Expand All'=>'lihat Semua Cabang',
	'Show All PC'=>'lihat Semua PC',
	'Export To Excel'=>'Export Ke Excel',
	'NB : SIW file name format must be :'=>'NB : Format Nama SIW File Harus :',
	' licenses'=>'lisensi',
	'One license'=>'Satu lisensi',
	'a License'=>'lisensi',
	'SIW Files'=>'Daftar File SIW',
	'Type License'=>'Tipe Lisensi',
	
);
